import type { Capture, TasteRadarPoint } from '@/lib/aesthetica/types'

export const sampleTasteRadar: TasteRadarPoint[] = [
  {
    id: 'minimal_maximal',
    axis: 'Minimal',
    leftLabel: 'Minimal',
    rightLabel: 'Maximal',
    value: 74,
  },
  {
    id: 'structured_relaxed',
    axis: 'Structured',
    leftLabel: 'Structured',
    rightLabel: 'Relaxed',
    value: 61,
  },
  {
    id: 'neutral_color',
    axis: 'Neutral',
    leftLabel: 'Neutral',
    rightLabel: 'Color-forward',
    value: 58,
  },
  {
    id: 'classic_experimental',
    axis: 'Classic',
    leftLabel: 'Classic',
    rightLabel: 'Experimental',
    value: 52,
  },
  {
    id: 'casual_formal',
    axis: 'Casual',
    leftLabel: 'Casual',
    rightLabel: 'Formal',
    value: 67,
  },
]

export const sampleCaptures: Capture[] = [
  {
    id: 'cap_0184',
    capturedAtISO: '2026-02-14T18:12:00.000Z',
    locationHint: 'SoHo',
    summary:
      'Reticle-centered crop. Relaxed neutral tailoring with crisp proportions and minimal accessories.',
    aestheticOneLiner: 'Relaxed neutral tailoring.',
    latencySeconds: 4.6,
    outfitEmbeddingId: 'emb_outfit_9f2a',
    radarDelta: { structured_relaxed: 4, minimal_maximal: 2, casual_formal: 1 },
    segments: [
      {
        id: 'seg_top_1',
        type: 'top',
        summary: 'Boxy wool overshirt, soft shoulder, matte charcoal.',
        matches: [
          {
            id: 'prd_101',
            title: 'Charcoal Wool Overshirt',
            retailer: 'COS',
            price: '$145',
            tier: 'closest',
            score: 0.91,
            url: '#',
          },
          {
            id: 'prd_102',
            title: 'Heavyweight Flannel Shirt Jacket',
            retailer: 'Uniqlo U',
            price: '$69',
            tier: 'alternative',
            score: 0.86,
            url: '#',
          },
          {
            id: 'prd_103',
            title: 'Italian Wool Overshirt',
            retailer: 'Lemaire',
            price: '$690',
            tier: 'premium',
            score: 0.88,
            url: '#',
          },
        ],
      },
      {
        id: 'seg_bottom_1',
        type: 'bottom',
        summary: 'Wide-leg trouser, mid-rise, clean hem, deep black.',
        matches: [
          {
            id: 'prd_201',
            title: 'Wide-Leg Tailored Trouser',
            retailer: 'Arket',
            price: '$119',
            tier: 'closest',
            score: 0.9,
            url: '#',
          },
          {
            id: 'prd_202',
            title: 'Pleated Wide Pants',
            retailer: 'Muji',
            price: '$59',
            tier: 'alternative',
            score: 0.83,
            url: '#',
          },
          {
            id: 'prd_203',
            title: 'Pleated Wool Trouser',
            retailer: 'The Row',
            price: '$990',
            tier: 'premium',
            score: 0.87,
            url: '#',
          },
        ],
      },
      {
        id: 'seg_shoes_1',
        type: 'shoes',
        summary: 'Minimal leather loafer, rounded toe, low shine.',
        matches: [
          {
            id: 'prd_301',
            title: 'Leather Loafer',
            retailer: 'Vagabond',
            price: '$140',
            tier: 'closest',
            score: 0.89,
            url: '#',
          },
          {
            id: 'prd_302',
            title: 'Penny Loafer',
            retailer: 'G.H.Bass',
            price: '$99',
            tier: 'alternative',
            score: 0.82,
            url: '#',
          },
          {
            id: 'prd_303',
            title: 'Soft Leather Loafer',
            retailer: 'Jil Sander',
            price: '$920',
            tier: 'premium',
            score: 0.84,
            url: '#',
          },
        ],
      },
    ],
  },
  {
    id: 'cap_0183',
    capturedAtISO: '2026-02-13T21:06:00.000Z',
    locationHint: 'Williamsburg',
    summary:
      'Outerwear-forward silhouette. High-contrast pattern accent with muted base layers.',
    aestheticOneLiner: 'Muted base, pattern accent.',
    latencySeconds: 4.1,
    outfitEmbeddingId: 'emb_outfit_8c14',
    radarDelta: { neutral_color: 3, classic_experimental: 2 },
    segments: [
      {
        id: 'seg_outer_2',
        type: 'outerwear',
        summary: 'Cropped jacket with graphic weave, high contrast.',
        matches: [
          {
            id: 'prd_401',
            title: 'Cropped Pattern Jacket',
            retailer: 'Our Legacy',
            price: '$410',
            tier: 'closest',
            score: 0.88,
            url: '#',
          },
          {
            id: 'prd_402',
            title: 'Jacquard Zip Jacket',
            retailer: 'Zara',
            price: '$89',
            tier: 'alternative',
            score: 0.8,
            url: '#',
          },
          {
            id: 'prd_403',
            title: 'Textured Cropped Jacket',
            retailer: 'Dries Van Noten',
            price: '$1150',
            tier: 'premium',
            score: 0.84,
            url: '#',
          },
        ],
      },
    ],
  },
]

